# Generated by Django 3.2.4 on 2021-08-28 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infographic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infographic',
            name='price',
            field=models.IntegerField(default=30),
        ),
    ]
