# Generated by Django 3.2.4 on 2021-08-28 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infographic', '0002_infographic_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infographic',
            name='price',
            field=models.FloatField(default=30),
        ),
    ]
