# Generated by Django 3.2.4 on 2021-07-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('ESP', 'Espote'), ('CLT', 'Cultura'), ('CNM', 'Comida na mesa')], max_length=3)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('responsible', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('prerequisites', models.CharField(max_length=500)),
            ],
        ),
    ]
