# Generated by Django 3.2.4 on 2021-08-01 23:42

from django.db import migrations, models
import updates.models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0002_auto_20210730_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='imagem',
            field=models.ImageField(default='updates/socialist-dog.jpg', upload_to=updates.models.upload_to),
        ),
        migrations.AlterField(
            model_name='update',
            name='titulo',
            field=models.CharField(max_length=55),
        ),
    ]
